config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'pages/settings'

  get 'pages/engagement'

  get 'pages/users'

  get 'pages/newuser'

  get 'pages/teams'

  get 'pages/newteam'

  get 'pages/action'

  get 'pages/questions'

  get 'pages/profile'

  get 'pages/stats'

  get 'pages/compare'

  get 'pages/organisation'

  get 'pages/opportunities'

  get 'pages/reward'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def engagement
  end

  def settings
  end

  def home
  end

  def users
  end

  def teams
  end

  def newuser
  end

  def newteam
  end

  def questions
  end

  def action
  end

  def profile
  end

  def stats
  end

  def compare
  end

  def organisation
  end

  def opportunities
  end

  def reward
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_menu.html.erb
<div class="list-group">
   <% if current_page?(pages_engagement_path) or current_page?(pages_organisation_path) or current_page?(pages_opportunities_path) -%>
      <%= link_to "Insights", pages_engagement_path, :class => "list-group-item list-group-item-action active" %>
   <% else -%>
      <%= link_to "Insights", pages_engagement_path, :class => "list-group-item list-group-item-action" %>
   <% end -%>

  <% if current_page?(pages_action_path) -%>
      <%= link_to "Action Board", pages_action_path, :class => "list-group-item list-group-item-action active" %>
   <% else -%>
      <%= link_to "Action Board", pages_action_path, :class => "list-group-item list-group-item-action" %>
   <% end -%>

   <% if current_page?(pages_questions_path) -%>
      <%= link_to "Questions", pages_questions_path, :class => "list-group-item list-group-item-action active" %>
   <% else -%>
      <%= link_to "Questions", pages_questions_path, :class => "list-group-item list-group-item-action" %>
   <% end -%>

  <% if current_page?(pages_users_path) or current_page?(pages_newuser_path) or current_page?(pages_teams_path) or current_page?(pages_newteam_path) or current_page?(pages_stats_path) -%>
      <%= link_to "Users", pages_users_path, :class => "list-group-item list-group-item-action active" %>
   <% else -%>
      <%= link_to "Users", pages_users_path, :class => "list-group-item list-group-item-action" %>
   <% end -%>

  <% if current_page?(pages_settings_path) -%>
      <%= link_to "Settings", pages_settings_path, :class => "list-group-item list-group-item-action active" %>
   <% else -%>
      <%= link_to "Settings", pages_settings_path, :class => "list-group-item list-group-item-action" %>
   <% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insights Admin Prototype</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if current_page?(pages_compare_path) %>
    	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <% end %>
    <% if current_page?(pages_engagement_path) %>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/easy-pie-chart/2.1.6/jquery.easypiechart.js"></script>
    <% end %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.js"></script>
  </head>

  <body>
    <div class="color">
    	<%= render "layouts/nav" %>
    		<div class="container">
    			<div class="row space">
      			<div class="col-md-3">
  			      <%= render "layouts/menu" %>
  			    </div>
  				<div class="col-md-9">
  					<% unless current_page?(pages_action_path) %>
  						<div class="card">
  	 						<div class="card-body">
  					  			<%= yield %>
  					  		</div>
  					  	</div>
  					<% else %>
  					  	<%= yield %>
  					<% end %>
  				</div>
      		</div>
  		</div>
    </div>
		<script type="text/javascript">
						$(function () {
			  $('[data-toggle="tooltip"]').tooltip()
			})
		</script>
  </body>
</html>

app/views/pages/compare.html.erb
<%-# Header starts -%>
<div class="row">
	<div class="col-12">
			<nav aria-label="breadcrumb" role="navigation">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item"><%= link_to "Insights", pages_engagement_path %></li>
			    <li class="breadcrumb-item active" aria-current="page">Compare All</li>
			  </ol>
			</nav>
	</div>
	<div class="col-12">
	</div>
</div>
<%-# Header ends -%>

<%-# Separator -%>

<div class="row">
	<div class="col-12">
		<hr>
	</div>
</div>

<%-# Stats -%>

<div class="row">
	<div class="col-12">
		<div id="myDiv">		
		</div>
	</div>
</div>


<script>
   var data = [
  {
    z: [[5, 5, 6, 5, 7, 7, 6, 8, 6, 4], [4, 6, 8, 8, 8, 7.3, 5, 4, 2, 5], [6, 6, 6, 5, 8, 4, 7, 8, 6, 6]],
    x: ['The organisation, strategy & culture', 'Communication', 'My work', 'Management', 'Leadership', 'Opportunities', 'Reward & recognition', 'Training & development', 'Quality of life', 'Teamwork'],
    y: ['Account Management', 'Product & Engineering', 'Marketing'],
    type: 'heatmap'
  }
];

Plotly.newPlot('myDiv', data);
</script>

app/views/pages/engagement.html.erb
<%-# Header starts -%>
<div class="row">
	<div class="col-12">
		<div class="gap">
			<nav aria-label="breadcrumb" role="navigation">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item active" aria-current="page">Insights</li>
			    <li class="breadcrumb-item active" aria-current="page">Engagement</li>
			  </ol>
			</nav>
		</div>
	</div>
	<div class="col-12">
		<div class="float-left">
			<div class="dropdown">
				<button class="btn btn-light dropdown-toggle small" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Whole Company
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					<a class="dropdown-item" href="#">Account Management</a>
					<a class="dropdown-item" href="#">Product & Engineering</a>
					<a class="dropdown-item" href="#">London</a>
					<a class="dropdown-item" href="#">Sheffield</a>
				</div>
			</div>
		</div>
		<div class="float-right">
			<%= link_to pages_compare_path do %>
				<button type="button" class="btn btn-light ">Compare all teams</button>
			<% end %>
			<button type="button" class="btn btn-warning ">Download Report</button>
		</div>
	</div>
</div>
<%-# Header ends -%>

<%-# Separator -%>

<div class="row">
	<div class="col-12">
		<hr>
	</div>
</div>

<%-# Gauge Starts -%>

<div class="row">
	<div class="col-5">
		
		<div id="gauge" style="width:330px; height:260px"></div>
	</div>
	<div class="col-7">
		<div class="space">
			<h2 class="space">7/10 is a great score <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="" data-original-title="This score is calculated as a cumulative moving average across all 10 key drivers of engagement. e.g Communication, My work, Leadership, Teamwork etc"></em></h2>
			<p>This engagement score is a great way of keeping the pulse of how your employees are feeling, their dedication to work, sense of purpose and happiness in their job...</p>
			<div class="collapse" id="viewdetails">
				<p>With a score of 7/10, you can expect some of the following business benefits:</p>
					<ul>
						<li>65% less staff turnover</li>
						<li>4% increase in operating margin</li>
						<li>Another benefit</li>
					</ul>
					<div class="spacea">
						<a href "#" class="gap" data-toggle="modal" data-target="#myModal1">See how we measure engagement</a>
					</div>

			</div>
          
          	<a href="#" data-toggle="collapse" data-target="#viewdetails">View details <em class="fa fa-chevron-down"></em></a>
		</div>
	</div>
</div>

<%-# Graph starts -%>
<div class="row">
	<div class="col-12">
		<canvas id="line-chart" width="800" height="250"></canvas>
	</div>
</div>


<%-# Strengths/Weaknesses -%>

<div class="row space">
	<div class="col-6">
		<h2 class="text-center">Your Strengths <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="Calculated from 4250 survey responses since Jan 2017"></em></h2>
		<p class="text-center text-muted small">UPPER 5 DRIVERS</p>
		<%= link_to pages_organisation_path do %>
		  	<div class="bottomLinks">
		    	<p class="pt-1">The organisation, strategy &amp; culture <span class="float-right text-success">9.5 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 95%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		<% end -%>
		<a href="/pages/organisation">
		  	<div class="bottomLinks">
		    	<p class="pt-1">Communication <span class="float-right text-success">9.2 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 92%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		</a>
		<a href="/pages/organisation">
		  	<div class="bottomLinks">
		    	<p class="pt-1">My work <span class="float-right text-success">8.7 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 87%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		</a>
		<a href="/pages/organisation">
		  	<div class="bottomLinks">
		    	<p class="pt-1">Leadership <span class="float-right text-success">8.1 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 81%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		</a>
		<a href="/pages/organisation">
		  	<div class="bottomLinks">
		    	<p class="pt-1">Management <span class="float-right text-success">7.6 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 76%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		</a>
	</div>
	<div class="col-6">
		<h2 class="text-center">Your Weaknesses <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="Calculated from 3590 survey responses since Jan 2017"></em></h2>
		<p class="text-center text-muted small">LOWER 5 DRIVERS</p>
		<a href="/pages/organisation">
		<%= link_to pages_opportunities_path do %>
		  	<div class="bottomLinks">
		    	<p class="pt-1">Opportunities <span class="float-right text-danger">7.4 <i class="fa fa-chevron-right"></i></span> <span class="badge badge-success"> Quick Win Fixes!</span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 74%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		<% end -%>
		<%= link_to pages_reward_path do %>
		  	<div class="bottomLinks">
		    	<p class="pt-1">Reward & recognition <span class="float-right text-danger">7.1 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 71%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		<% end -%>
		<a href="/pages/organisation">
		  	<div class="bottomLinks">
		    	<p class="pt-1">Training & development <span class="float-right text-danger">6.3 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 63%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		</a>
		<a href="/pages/organisation">
		  	<div class="bottomLinks">
		    	<p class="pt-1">Teamwork <span class="float-right text-danger">6.1 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 61%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		</a>
		<a href="/pages/organisation">
		  	<div class="bottomLinks">
		    	<p class="pt-1">Quality of life <span class="float-right text-danger">5.7 <i class="fa fa-chevron-right"></i></span></p>
				<div class="progress progress-custom">
					<div class="progress-bar bg-text-color" style="width: 57%" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
		  	</div>
		</a>	
	</div>
</div>


<script type="text/javascript">

$(function() {
   $('#easypiechart-4').easyPieChart({
       scaleColor: false,
       barColor: '#00adee'
   });
});
</script>

<script type="text/javascript">
  var g = new JustGage({
    id: "gauge",
    value: 6.7,
    min: 0,
    max: 10,
    gaugeWidthScale: 0.6,
    customSectors: [{
          	color: '#00ADEE',
            lo: 0,
            hi: 33
          },
          {
          	color: '#00ADEE',
            lo: 33,
            hi: 66
          },{
          	color: '#00ADEE',
            lo: 66,
            hi: 100
          }]
  });
</script>

<script>
new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov"],
    datasets: [{ 
        data: [6.2,7.4,6.8,7.4,6.8,8.0,8.2,7.9,8.0,7.1,7.0],
        label: "Engagement",
        borderColor: "#00adee",
        fill: false
      }
    ]
  },
  options: {
    legend: {
    		display: false,
            position: 'bottom',
            labels: {
                fontFamily: 'Lato',
                fontSize: 14,
            }
        },
    scales : {
        xAxes : [ {
            gridLines : {
                display : true,
            }
        } ],
        yAxes : [ {
            gridLines : {
                display : true,
            }
        } ]
    }

  },


});
</script>

<div class="modal fade bd-example-modal-lg" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">How we measure engagement</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>It's pretty intuitive to make the leap that engaged employees have a big impact on business success... but what actually makes an engaged employee? What are the drivers and differentiators between engaged and disengaged employees?</p>

				<p>In order to measure engagement, we first need to understand the factors that DRIVE or INFLUENCE employee engagement. There are a plethora of questions, models (i.e. Gallup’s Q12), and approaches to determine this, but we prefer to lean on studies from credible sources that identify the key drivers of engagement. We’ve collected a few of these studies, and outlined the factors they found below:</p>
      </div>
    </div>
  </div>
</div>	

app/views/pages/home.html.erb
<section class="row">
	<div class="col-sm-12">
		<h2 class="text-center space homey">
			Hey Shaun, see what's been happening at Perkbox this week...
		</h2>
	</div>
</section>


<div class="row">
	<div class="col-4">
		<div class="card">
		  <div class="card-body text-center">
		    <h1 class="text-center">7/<span class="small text-muted">10</span></h1>
		    <p class= "text-muted text-center">ENGAGEMENT SCORE</p>
		    <%= link_to "View engagement score", pages_engagement_path %>
		  </div>
		</div>
	</div>
	<div class="col-4">
		<div class="card">
		  <div class="card-body text-center">
		    <h1 class="text-center">57.5%</h1>
		    <p class= "text-muted text-center">SURVEY RESPONSE RATE</p>
		    <%= link_to "View participation stats", pages_stats_path %>
		  </div>
		</div>
	</div>
	<div class="col-4">
		<div class="card">
		  <div class="card-body text-center">
		    <h1 class="text-center">4</h1>
		    <p class= "text-muted text-center">NEW USERS ADDED</em></p>
		    <%= link_to "Invite new user", pages_newuser_path %>
		  </div>
		</div>
	</div>
</div>

app/views/pages/newteam.html.erb
<%-# Header starts -%>
<div class="row">
	<div class="col-12">
			<nav aria-label="breadcrumb" role="navigation">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item"><%= link_to "Users", pages_users_path %></li>
			  	<li class="breadcrumb-item"><%= link_to "Teams", pages_teams_path %></li>
			    <li class="breadcrumb-item active" aria-current="page">Create new team</li>
			  </ol>
			</nav>
	</div>
</div>
<%-# Header ends -%>

<%-# Separator -%>

<div class="row">
	<div class="col-12">
		<hr>
	</div>
</div>

<%-# Stats -%>

<form class="form" action="#">
		<div class="form-group row">
			<label class="col-md-3 col-form-label">Team name</label>
			<div class="col-md-9">
				<input type="text" name="regular" class="form-control" placeholder="First name">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-md-3 col-form-label">Parent team</label>
			<div class="col-md-9">
				<select class="custom-select form-control">
					<option selected="">Perkbox</option>
					<option value="1">Account management</option>
					<option value="2">Product &amp; Engineering</option>
					<option value="2">London</option>
					<option value="2">Sheffield</option>
				</select>
			</div>
		</div>
	<section class="row">
		<br>
		<div class="col-md-6">
		</div>
		<div class="col-md-6">
			<div class="float-right">
				<button type="button" class="btn btn-md btn-warning">Create new team</button>
			</div>
		</div>
	</section>
</form>

app/views/pages/opportunities.html.erb
<%-# Header starts -%>
<div class="row">
	<div class="col-12">
		<div class="gap">
			<nav aria-label="breadcrumb" role="navigation">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item"><%= link_to "Insights", pages_engagement_path %></li>
			  	<li class="breadcrumb-item"><%= link_to "Engagement", pages_engagement_path %></li>
			    <li class="breadcrumb-item active" aria-current="page">Opportunities</li>
			  </ol>
			</nav>
		</div>
	</div>
	<div class="col-12">
		<div class="float-left">
			<div class="dropdown">
				<button class="btn btn-light dropdown-toggle small" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Whole Company
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					<a class="dropdown-item" href="#">Account Management</a>
					<a class="dropdown-item" href="#">Product & Engineering</a>
					<a class="dropdown-item" href="#">London</a>
					<a class="dropdown-item" href="#">Sheffield</a>
				</div>
			</div>
		</div>
		<div class="float-right">
			<%= link_to pages_compare_path do %>
				<button type="button" class="btn btn-light ">Compare all teams</button>
			<% end %>
			<button type="button" class="btn btn-warning ">Download Report</button>
		</div>
	</div>
</div>
<%-# Header ends -%>

<%-# Separator -%>

<div class="row">
	<div class="col-12">
		<hr>
	</div>
</div>

<%-# Gauge Starts -%>

<div class="row">
	<div class="col-5">
		
		<div id="gauge" style="width:330px; height:260px"></div>
	</div>
	<div class="col-7">
		<div class="space">
			<h2 class="space">7/10 is a good score <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="" data-original-title="This score is calculated as a cumulative moving average of all the opportunities questions."></em></h2>
			<p>Here's what it means:</p>
			<div class="collapse" id="viewdetails">
				<ul>
						<li>Most people feel they have future career opportunities at Perkbox</li>
						<li>Some staff feel they have the opportunity to develop skills to achieve career goals</li>
						<li>Most people feel Perkbox focuses on promoting the people best equipped to meet the future needs of the company</li>
					</ul>
				<div class="spacea">
					<a href "#" data-toggle="modal" data-target="#myModal1">See a breakdown of the question responses</a>
				</div>

			</div>
          
          	<a href="#" data-toggle="collapse" data-target="#viewdetails">View details <em class="fa fa-chevron-down"></em></a>
		</div>
	</div>
</div>

<%-# Graph starts -%>
<div class="row">
	<div class="col-12">
		<canvas id="line-chart" width="800" height="250"></canvas>
	</div>
</div>



<%-# Our Recommendations -%>
<div class="row space">
	<div class="col-12">
		<h2>What top performing companies are doing</h2>
		<div class="row less">
			<div class="col-12">
				<table class="table">
				  <tbody>
				    <tr>
				      <td> Give everyone a £50/month training budget <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="" data-original-title="Here's a short description of how it works and what's involved in executing this action item..."></em> <span class="badge badge-success float-right">Quick Win Fix</span></td>
				    </tr>
				    <tr>
				      <td>Provide free access to Skillshare <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="" data-original-title="Here's a short description of how it works and what's involved in executing this action item..."></em></td>
				    </tr>
				    <tr>
				      <td>Quarterly access to a career development coach <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="" data-original-title="Here's a short description of how it works and what's involved in executing this action item..."></em></td>
				    </tr>
				  </tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<%-# What's being said -%>
<div class="row">
	<div class="col-12">
		<h2>What's being said <em class="fa fa-question-circle" data-toggle="tooltip" data-placement="right" title="" data-original-title="Here's what your employees are saying in the surveys..."></em></h2>
		<div class="row less">
			<div class="col-12">
				<table class="table">
				  <tbody>
				    <tr>
				      <td>"I love that we get a beer trolley and how chilled it is"</td>
				      <td>Nov 2017</td>
				    </tr>
				    <tr>
				      <td>"Perkbox is like no other company I've worked at"</td>
				      <td>Nov 2017</td>
				    </tr>
				    <tr>
				      <td>"I wish things were a little more formal and we had to wear suits"</td>
				      <td>Nov 2017</td>
				    </tr>
				  </tbody>
				</table>
				<a href="#" class="">Show all <em class="fa fa-chevron-down"></em></a>
			</div>
		</div>
	</div>
	
</div>

  


<script type="text/javascript">

$(function() {
   $('#easypiechart-4').easyPieChart({
       scaleColor: false,
       barColor: '#00adee'
   });
});
</script>

<script type="text/javascript">
  var g = new JustGage({
    id: "gauge",
    value: 7,
    min: 0,
    max: 10,
    gaugeWidthScale: 0.6,
    customSectors: [{
          	color: '#00ADEE',
            lo: 0,
            hi: 33
          },
          {
          	color: '#00ADEE',
            lo: 33,
            hi: 66
          },{
          	color: '#00ADEE',
            lo: 66,
            hi: 100
          }]
  });
</script>

<script>
new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov"],
    datasets: [{ 
        data: [6.2,7.4,6.8,7.4,6.8,8.0,8.2,7.9,8.0,7.1,7.0],
        label: "Organisation",
        borderColor: "#00adee",
        fill: false
      }
    ]
  },
  options: {
    legend: {
    		display: false,
            position: 'bottom',
            labels: {
                fontFamily: 'Lato',
                fontSize: 14,
            }
        },
    scales : {
        xAxes : [ {
            gridLines : {
                display : true,
            }
        } ],
        yAxes : [ {
            gridLines : {
                display : true,
            }
        } ]
    }

  },


});
</script>

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Question Responses</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-bordered table-responsive">
				  <thead>
				    <tr>
				      <th scope="col">Question</th>
				      <th scope="col">Responses</th>
				      <th scope="col">Response rate %</th>
				      <th scope="col">Score/10</th>
				    </tr>
				  </thead>
				  <tbody>
				    <tr>
				      <td>I feel that I have future career opportunities at Perkbox</td>
				      <td>145</td>
				      <td>67</td>
				      <td class="text-danger">3</td>
				    </tr>
				    <tr>
				      <td>I have opportunities to develop skills to achieve my career goals</td>
				      <td>97</td>
				      <td>56</td>
				      <td class="text-danger">5</td>
				    </tr>
				    <tr>
				      <td>Perkbox focuses on promoting the people best equipped to meet the future needs of the company</td>
				      <td>50</td>
				      <td>20</td>
				      <td class="text-danger">4</td>
				    </tr>
				    <tr>
				      <td>If I perform well in my role, it will lead to opportunities for me to progress</td>
				      <td>145</td>
				      <td>67</td>
				      <td class="text-success">7</td>
				    </tr>
				    <tr>
				      <td>The performance review process helps me focus my work efforts to help the organisation achieve its goals</td>
				      <td>195</td>
				      <td>87</td>
				      <td class="text-success">9</td>
				    </tr>
				  </tbody>
				</table>
      </div>
    </div>
  </div>
</div>	